# This is a basic workflow to help you get started with Actions

name: create-file

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request: 
      types: [ opened ]
      branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create-file"
  create-file:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Setup python and run script
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
      - name: Run python script
        run: python ./createtext.py
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: example-text-file
          id: generate_file
          path: ./example.txt
       # Testing post Artifact as Comment on PR
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: 1
          body: This is a comment + ${{ steps.generate_file.outputs }}
        
          
         
        
  
