name: local push

on: 
  workflow_dispatch:
  #repository_dispatch:
   # types: post-comment 

jobs:
  # This workflow contains a single job called "post-comment"
  post-comment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
    #  - name: Create or Update Comment
   #     uses: peter-evans/create-or-update-comment@v2.0.0
  #      with:
 #         issue-number: 1
#          body: This is a comment
          
          #${{ github.event.number }}
          
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
