name: local push

on: 
  workflow_dispatch:
  #repository_dispatch:
   # types: post-comment 

jobs:
  # This workflow contains a single job called "post-comment"
  post-comment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      # Setup python and run script
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
      - name: Run python script
        run: python ./createtext.py
      - id: get-file-body
        run: |
          body="$(cat example.txt)"
          echo "::set-output name=body::$body"
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: 2
          body: ${{ steps.get-file-body.outputs.body }}
      
