name: manually re-running actions

on: 
  repository_dispatch:
    types: post-comment 

jobs:
  # This workflow contains a single job called "post-comment"
  post-comment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.number }}
          body: This is a comment
