name: post-pr-artifact

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  post-pr-artifact:
    runs-on: ubuntu-latest

    steps:
       - name: workflow artifact pull request comment
         uses: tonyhallett/artifacts-url-comments@v1.1.0
          
